name: Check PHP code style

on: [push, pull_request]

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - uses: ramsey/composer-install@v4
      - run: vendor/bin/pint --test src tests config database
